# Route on the /.
app_general:
    path: /
    controller: App\Controller\GeneralController::index

# Route of app_register on url /register.
app_register:
    path: /register
    controller: App\Controller\RegistrationController::register

# Route of app_login on url /login.
app_login:
    path: /login
    controller: App\Controller\LoginController::login

# Route of app_logout on url /logout.
app_logout:
    path: /logout
    controller: App\Controller\LoginController::logout

# Route of app_dashboard on url /dashboard.
app_dashboard:
    path: /dashboard
    controller: App\Controller\GeneralController::dashboard

# Route of app_profile on url /profile/{id}.
app_profile:
    path: /profile/{id}
    controller: App\Controller\GeneralController::profile

# Route of app_exams on url /exam/{id}.
app_exams:
    path: /exams
    controller: App\Controller\GeneralController::exams

# Route of app_exams on url /exam/{id}.
app_createProfile:
    path: /create-profile/{id}
    controller: App\Controller\GeneralController::createProfile

# Route of app_exams on url /exam/{id}.
app_editProfile:
    path: /edit-profile/{id}
    controller: App\Controller\GeneralController::editProfile

# Route fro aplly_exam on url /apply-exam/{profileId}/{examId}
apply_exam:
    path: /apply-exam/{profileId}/{examId}
    controller: App\Controller\GeneralController::applyExam

# Route of app_appliedExams on url user-exams/{id}
app_appliedExams:
    path: user-exams/{id}
    controller: App\Controller\GeneralController::appliedExams

# Route of app_startExams on url start-exam/{examId}/{profileId}
app_startExam:
    path: start-exam/{examId}/{profileId}
    controller: App\Controller\GeneralController::startExam

# Route of app_questionList on url questions/{userId}/{examId}
app_questionList:
    path: questions/{userId}/{examId}
    controller: App\Controller\GeneralController::questions

# Route of app_openQuestion on url open-question/{userId}/{examId}/{quesId}
app_openQuestion:
    path: open-question/{userId}/{examId}/{quesId}
    controller: App\Controller\GeneralController::openQuestion

# Route of app_admin on url /admin
app_admin:
    path: /admin
    controller: App\Controller\AdminController::index

# Route of create_exam on url /admin/create-exam/
create_exam:
    path: /admin/create-exam/
    controller: App\Controller\AdminController::createExam

# Route of your_exams on url /admin/your-exams/{id}
your_exams:
    path: /admin/your-exams/{id}
    controller: App\Controller\AdminController::yourExams

# Route of delete_exams on url /admin/delete-exams/{examId}
delete_exams:
    path: /admin/delete-exams/{examId}
    controller: App\Controller\AdminController::deleteExams

# Route of adminexam_details on url /admin/your-exam-detail/{examId}
adminexam_details:
    path: /admin/your-exam-detail/{examId}
    controller: App\Controller\AdminController::yourExamDetail

# Route of app_adminQuestion on url /admin/questions
app_adminQuestion:
    path: /admin/questions
    controller: App\Controller\AdminController::allQuestions

# Route of exam_submit on url /exam-submit/{examId}
exam_submit:
    path: /exam-submit/{examId}
    controller: App\Controller\GeneralController::examSubmit

# Route of exam_result on url /result/{gottenMarks}/{correctAns}/{incorrectAns}
exam_result:
    path: /result/{gottenMarks}/{correctAns}/{incorrectAns}
    controller: App\Controller\GeneralController::result

# Route of exam_allResult on url /results/{examId}
exam_allResult:
    path: /results/{examId}
    controller: App\Controller\GeneralController::allResult
